/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct PUBLISH_ARGS {
	int value;
	char *topic;
};
typedef struct PUBLISH_ARGS PUBLISH_ARGS;

struct RETRIEVER_ARGS {
	char *topic;
};
typedef struct RETRIEVER_ARGS RETRIEVER_ARGS;

struct RETRIEVE_RESULT {
	int status;
	struct {
		u_int values_len;
		int *values_val;
	} values;
};
typedef struct RETRIEVE_RESULT RETRIEVE_RESULT;

#define BROKER_PROG 0x20000001
#define BROKER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PUBLISH 1
extern  int * publish_1(PUBLISH_ARGS , CLIENT *);
extern  int * publish_1_svc(PUBLISH_ARGS , struct svc_req *);
#define RETRIEVE 2
extern  RETRIEVE_RESULT * retrieve_1(RETRIEVER_ARGS , CLIENT *);
extern  RETRIEVE_RESULT * retrieve_1_svc(RETRIEVER_ARGS , struct svc_req *);
extern int broker_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PUBLISH 1
extern  int * publish_1();
extern  int * publish_1_svc();
#define RETRIEVE 2
extern  RETRIEVE_RESULT * retrieve_1();
extern  RETRIEVE_RESULT * retrieve_1_svc();
extern int broker_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_PUBLISH_ARGS (XDR *, PUBLISH_ARGS*);
extern  bool_t xdr_RETRIEVER_ARGS (XDR *, RETRIEVER_ARGS*);
extern  bool_t xdr_RETRIEVE_RESULT (XDR *, RETRIEVE_RESULT*);

#else /* K&R C */
extern bool_t xdr_PUBLISH_ARGS ();
extern bool_t xdr_RETRIEVER_ARGS ();
extern bool_t xdr_RETRIEVE_RESULT ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
