/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_PUBLISH_ARGS (XDR *xdrs, PUBLISH_ARGS *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->topic, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RETRIEVER_ARGS (XDR *xdrs, RETRIEVER_ARGS *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->topic, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RETRIEVE_RESULT (XDR *xdrs, RETRIEVE_RESULT *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->values.values_val, (u_int *) &objp->values.values_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
