/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "../include/rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
publish_1(PUBLISH_ARGS arg1,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PUBLISH,
		(xdrproc_t) xdr_PUBLISH_ARGS, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RETRIEVE_RESULT *
retrieve_1(RETRIEVER_ARGS arg1,  CLIENT *clnt)
{
	static RETRIEVE_RESULT clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RETRIEVE,
		(xdrproc_t) xdr_RETRIEVER_ARGS, (caddr_t) &arg1,
		(xdrproc_t) xdr_RETRIEVE_RESULT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
